# Generated by Django 2.2 on 2020-12-09 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('club', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('division', models.CharField(max_length=1)),
                ('cantJugadores', models.IntegerField()),
                ('amonestados', models.IntegerField()),
                ('expulsados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numLinePerdidos', models.IntegerField()),
                ('numScrumPerdidos', models.IntegerField()),
                ('numPenalesEnContra', models.IntegerField()),
                ('numPelotasCaidas', models.IntegerField()),
                ('numConversionesErrados', models.IntegerField()),
                ('numTaclesErrados', models.IntegerField()),
                ('numPaseFoword', models.IntegerField()),
                ('numDropErrados', models.IntegerField()),
                ('numMaulErrados', models.IntegerField()),
                ('numRuckErrados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('lugar', models.CharField(max_length=50)),
                ('numLine', models.IntegerField()),
                ('numScrum', models.IntegerField()),
                ('numPenales', models.IntegerField()),
                ('tri', models.IntegerField()),
                ('numConversiones', models.IntegerField()),
                ('numDrop', models.IntegerField()),
                ('numTacles', models.IntegerField()),
                ('numMaul', models.IntegerField()),
                ('numRuck', models.IntegerField()),
                ('cantPases', models.IntegerField()),
                ('equipo_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuEquipo', to='core.Equipo')),
                ('equipo_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OtroEquipo', to='core.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=25)),
                ('apellido', models.CharField(default='', max_length=25)),
                ('dni', models.IntegerField()),
                ('tel', models.IntegerField()),
                ('posicion', models.CharField(choices=[('0', 'DESCONOCIDO'), ('1', 'Pilar Izquierdo'), ('2', 'Hooker'), ('3', 'Pilar Derecho'), ('4', 'Segunda Linea Izquierdo'), ('5', 'Segunda Linea Derecho'), ('6', 'Ala Derecho'), ('7', 'Ala Izquierdp'), ('8', '8'), ('9', 'Medio Scrum'), ('10', 'Apertura'), ('11', 'Wing Izquierdo'), ('12', 'Primer Centro'), ('13', 'Segundo Centro'), ('14', 'Wing Derecho'), ('15', 'Full Back')], default='DESCONOCIDO', max_length=50)),
                ('asistenciaComp', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('amonestado', models.BooleanField(default=False)),
                ('expulsado', models.BooleanField(default=False)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Error')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Partido')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=25)),
                ('apellido', models.CharField(default='', max_length=25)),
                ('dni', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Equipo')),
            ],
        ),
    ]
